# Generated by Django 3.0.4 on 2020-03-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('length', models.IntegerField(default=0, null=True)),
                ('width', models.IntegerField(default=0, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
